SRC_URI_append = " \
  file://0001-arm-dts-Enable-mxs-dcp-by-default.patch \
  file://0002-crypto-mxs-dcp-Implement-reference-keys.patch \
  file://0003-KEYS-add-symmetric-key-type.patch \
  file://0004-KEYS-add-symmetric-key-test-module.patch \
  file://0005-KEYS-add-CAAM-based-symmetric-key-subtype.patch \
  file://0006-KEYS-add-DCP-based-symmetric-key-subtype.patch \
  file://0007-dm-crypt-Add-support-for-symmetric-keys.patch \
  file://0008-fscrypt-Add-support-for-key-types-other-than-logon.patch \
  file://0009-fscrypt-Enable-key-lookup-on-custom-keyring.patch \
  file://0010-ubifs-Add-mount-option-support-for-global-keyring.patch \
  file://0011-ubifs-allow-usage-of-symmetric-key-type-for-UBIFS-en.patch \
  file://0012-symmetric_keys-Fix-key-buffer-usage.patch \
"
